### ISSUE TITLE
애그리거트 확장 

### ISSUE THREAD

**Issue by maggggggggggggie** [java-dev-study/Domain-Driven-Design#10]
ID 로 애그리거트를 참조하면 리포지터리마다 다른 저장소를 사용하도록 구현할때 확장이 용이하다고 하지만..
실제 개발자가 신규개발, 유지보수 외 데이터에 직접 접근해서 확인할 때는 용이하지 않을 것 같습니다.
애그리거트별로 다른 구현 기술을 사용해보신 분들의 이야기를 듣고 싶습니다.

**Comment by sgdo2021** [comment]
DDD 관점(더 깊숙히는 OOP 관점)에서 client(개발자든, 사용자든)가 객체의 값들을
직접접근하는 방법을 지양합니다. 왜냐하면 비즈니스로직을 처리하는 동안
데이터값이 변경되면 DB테이블에 넣어질시 데이터 정합성이 깨질 여지가 커지기 
때문입니다. 그래서 외부에서 데이터의 값들을 접근못하게 하고 값자체를 
초기화해서 변경불가한 상태로 필드를 구성하기도 합니다. (final 사용, 불변객체화)

그래도 개발자가 데이터에 직접 접근해서 확인하기 용이해지기 위해서라면...
그래서 테스트 중요성이 큰 것 같습니다. 이 안에서 assert검증을 해보는 것이죠
또는 runtime시 확인하고 싶다면 reflection 기술을 사용하면 된다고 알고 있습니다.
