### ISSUE TITLE
애그리거트 루트 객체 상태

### ISSUE THREAD

**Issue by Jo-YeonWoo** [java-dev-study/Domain-Driven-Design#11]
교재 103 페이지 중반부에 기재되어 있는 내용입니다.

`애그리거트는 여러 객체로 구성되기 때문에 한 객체만 상태가 정상이면 안 된다. 도메인 규칙을 지키려면 애그리거트에 속한 모든 객체가 정상 상태를 가져야 한다.`

위 문장에서 `정상 상태`가 의미하는 바와 `정상 상태`임을 어떻게 알 수 있을까요?

**Comment by sgdo2021** [comment]
vo 생각하면 state 값이 정상상태? 인 것이고

entity 생각하면 domain 비즈니스 로직 내 
Transcational 범위에서 영속성이 보장된 엔티티들이 외부에 
변경없이(이건 VO도 마찬가지) 테이블에 오류(ex.데드락)없이 잘 처리된 것을 말한게 아닐까 생각됩니다. 

정상상태 확인방법은 JUnitTest로 확인 ->  DB테이블에 데이터 잘들어왔나 확인정도?
