### ISSUE TITLE
트랜잭션과 애그리거트

### ISSUE THREAD

**Issue by beombeom1119** [java-dev-study/Domain-Driven-Design#13]
P. 102  - 대부분의 애그리거트는 한 개의 엔티티 객체만 갖는 경우가 많았다.
P. 110 - 트랜잭션 범위는 작을수록 좋다. DB의 예와 같이 한 트랜잭션에서는 한 개의 애그리거트만 수정해야 한다.

현재 시큐어 같은 경우는 한 건의 거래(트랜잭션)에 transact 관련 테이블들과 정산과 관련된 settlement 테이블들을 같이 추가하는데 
DDD를 효과적으로 만족시키기 위해 어떠한 방법을 사용할 수 있을까요?

**Comment by sgdo2021** [comment]
DDD 관점에서 봤을 때
application Layer에서 Facade패턴으로   
transact 관련 service, settlement 관련 service를 조합해서
처리하는 게 좋을 것 같아 보입니다.
