### ISSUE TITLE
DDD 사용목적

### ISSUE THREAD

**Issue by hava12** [java-dev-study/Domain-Driven-Design#14]
데이터베이스 위주의 개발 -> 트랜잭션 스크립트 패턴 -> DDD 
위처럼 설계 패턴의 흐름이 변화하게 된 이유는 어떤 것인지 함께 토론해보면 좋을 것 같습니다.

**Comment by sgdo2021** [comment]
원래는 웹개발의 역사와 별개로 DB가 가장 먼저 나온 걸로 알고 있습니다.

웹이 나중에 발명되고 이후에 기존의 DB구조에 웹이 맞춰야 하는 형태로 되어
DB 종속적인 개발은 필연적일 수밖에 없었던 게 아닌가 생각됩니다.

하지만 DB sql 로 종속되는 개발방식이 지금의 서비스 사용자들의 니즈에 맞추어
확장성, 유지보수성이 너무 떨어지게 되니 차츰 객체지향 설계로 웹개발이 
발전되어 가게 된 것 같습니다. 그 중심에 ORM 기술이 나왔고 
자바쪽에서는 JPA가 그 명성을 떨치고 있는 것 같습니다.

**Comment by sgdo2021** [comment]
그래서 이제 JPA를 통해서 DB 테이블을 `POJO`한 형태로 비즈니스 로직을
처리할 수 있게 됐고 유지보수성이 높아져 확장이 더욱 용이해졌습니다. 

사용자의 서비스 니즈 욕구에 더 부합하게 서비스를 더 많이 관심을
가지고 서비스 개발이 더 확장할 수 있게 되었습니다. 

AWS를 만든 아마존 창업자 제프베조스가 개발방식을 조직문화까지 확장시킨 
`MSA` 구상이 넷플릭스가 AWS를 도입하면서 세계적인 개발아키텍쳐 트랜드로 자리매김하게 되었고

마침 DDD가 MSA방식의 제프베조스가 생각한 개발조직문화에 시너지를 나게 해 
MSA와 함께 현 개발방식으로 각광받게 됐다고 생각합니다.  

아래가 제프베조스가 메일로 소개한 첫 MSA의 구상입니다. 참고하시면 좋을 것 같습니다 :)
https://ziponia.github.io/2019/05/20/react-native-sample.html
