### ISSUE TITLE
애그리거트 간 직접참조 간접참조 차이점

### ISSUE THREAD

**Issue by KimJuu** [java-dev-study/Domain-Driven-Design#16]
애그리거트 간 직접참조 간접참조 차이점에 대해서 이해가 잘 가지 않아서 같이 의논해봤으면해서 이슈 남깁니다.

**Comment by maggggggggggggie** [comment]
이해 할수 있습니다. !!!!!!!!!!!!!!!! 
같은 애그리거트 안에서는 직접참조를 해도 괜찮은걸로..
