### ISSUE TITLE
애그리거트 기반 패키지 구조

### ISSUE THREAD

**Issue by hava12** [java-dev-study/Domain-Driven-Design#18]
업무에서 혹은 개인적으로 공부할 때 애그리거트 패키지 구조를 어떤 식으로 짰는지, 이유는 무엇인지 경험 및 의견이 있다면 공유해주시면 감사합니다.

**Comment by KimJuu** [comment]
94페이지를 참고하시면 좋을것 같습니다. 할수있습니다!!!
