### ISSUE TITLE
특정 로직에 DIP 구현 가능? 

### ISSUE THREAD

**Issue by maggggggggggggie** [java-dev-study/Domain-Driven-Design#2]
오프라인 정산 관련된 부분이 하나의 로직에 다 구현되어 있습니다.  
도메인 주도 개발을 특정 부분에만 적용할 수도 있을까요 ?
첫 설계부터 큰 도메인 -> 하위 도메인 으로 연결 되어있는 듯 해서요. 
불필요한 setter 도 많고..

**Comment by KimJuu** [comment]
https://docs.google.com/document/d/1QmRN9kuT2N26IWmVB5tG2jUwhpebAzD1zhFF9haLRBQ/edit
