### ISSUE TITLE
JPA를 사용할시 FK가 없는 테이블로 구성된 RDBMS일때

### ISSUE THREAD

**Issue by sgdo2021** [java-dev-study/Domain-Driven-Design#21]
JPA를 사용할시 LazyLoading으로 성능최적화를 할 수 있는데요. 양방향으로 매핑시 fk가 있는 주인관계로 설정해주지
않으면 fetch모드로 Lazyloding이 될지 모르겠습니다. 현재 RDBMS table의 fk가 설정되지 않은 상태에서 JPA 도입을
할 수 있을까요?

**Comment by woo00oo** [comment]
할수있습니다!!
