### ISSUE TITLE
응용 서비스의 인터페이스 및 단위 테스트

### ISSUE THREAD

**Issue by Jo-YeonWoo** [java-dev-study/Domain-Driven-Design#24]
교재 211p.에서 `응용 서비스의 인터페이스`와 하단에서 `단위 테스트`에 대해 기술되어 있습니다.
아래는 해당 내용 중 일부입니다.

`표현 영역이 아닌 도메인 영역이나 응용 영역의 개발을 먼저 시작하면 응용 서비스 클래스가 먼저 만들어진다. 이렇게 되면 표현 영역의 단위 테스트를 위해 응용 서비스 클래스의 가짜 객체가 필요한데 이를 위해 인터페이스를 추가할 수도 있다. 하지만 Mockito와 같은 테스트 도구는 클래스에 대해서도 테스트용 대역 객체를 만들 수 있기 때문에 응용 서비스에 대한 인터페이스가 없어도 표현 영역을 테스트할 수 있다. 이는 결과적으로 응용 서비스에 대한 인터페이스 필요성을 약화시킨다.`

위 내용에 기재되어 있는 **Mockito**를 이용해 보신 분이 있으시다면 불필요한 인터페이스 추가 외에 다른 장점이 더 있으셨는지 궁금합니다.
또한, 지난 이슈 내용 중 언급된 `테스트 코드` 작성 시에도 **Mockito**를 이용하면 더 효율적일까요?

**Comment by woo00oo** [comment]
모키토 + junit5 사용 예제를 간단하게 공유해 드릴게요
given, when, then 패턴
