### ISSUE TITLE
테스트 코드 관리

### ISSUE THREAD

**Issue by im-Lily** [java-dev-study/Domain-Driven-Design#25]
구현해야 하는 기능이 많아지면 테스트 코드가 방대해질텐데, 이럴 경우에는 어떤 식으로 테스트 코드를 관리하는 것이 좋을까요?

**Comment by mooh2jj** [comment]
일단 레이어드 아키텍쳐면 각 레이어 컴포넌트 단위로 테스트를 만들고 메서드별로 기능테스트를 할수 있어요

**Comment by sgdo2021** [comment]
일단 레이어드 아키텍쳐면 각 레이어 컴포넌트 단위로 테스트를 만들고 
메서드별로 기능테스트를 할수 있어요
