### ISSUE TITLE
선점 잠금, 비선점 잠금, 오프라인 선점 잠금

### ISSUE THREAD

**Issue by WonSSSIK** [java-dev-study/Domain-Driven-Design#30]
제로페이, 서울사랑 상품권 같이 판매 금액이 정해져 있는 상품권의 판매 도메인에서
해당 금액이 모두 소진 됐을 때(판매 금액 10 억원, 1인당 70만원 한도), 판매를 종료 한다면 어떤 잠금을 사용하는게 좋을까요?

**Comment by woo00oo** [comment]
성공하세요.

**Comment by KimJuu** [comment]
저도도전
