### ISSUE TITLE
할인 쿠폰 애그리거트 구분

### ISSUE THREAD

**Issue by im-Lily** [java-dev-study/Domain-Driven-Design#32]
> p.234에서 할인 쿠폰을 두 개 이상 적용할 수 있다면 단일 할인 쿠폰 애그리거트는 총 결제 금액을 계산할 수 없다.

대부분 할인 쿠폰 애그리거트는 보통 단일 할인, 다중 할인 애그리거트로 구분해서 설계하나요?

**Comment by woo00oo** [comment]
끄읏!!!!!!!!!!!! 💯 🥇
