### ISSUE TITLE
공개 호스트 서비스 관련

### ISSUE THREAD

**Issue by woo00oo** [java-dev-study/Domain-Driven-Design#34]
책에서 언급된 상류 컴포넌트와 하류 컴포넌트를 결제 모듈 서비스에서 상류 컴포넌트는 엑심베이 시스템, 하류 컴포넌트는 가맹점 시스템으로 비유가 가능할 거 같습니다.
실무에서 여러 하류 컴포넌트의 요구사항들이 천차만별 입니다.
현재 시스템에서는 특정 요구사항에 따라서 하드 코딩으로 분기 처리가 되어 있어 유지보수가 어렵고, 핵심 도메인 기능을 파악하기 어려운 거 같습니다. 또 새로운 요구사항들이 생기면 하드 코딩으로 분기를 쳐야 합니다.
따라서 이러한 문제를 해결하기 위해서는 책에서 언급된 여러 하류 팀의 요구사항을 수용할 수 있는 API를 만들고 이를 서비스 형태로 공개해서 서비스의 일관성을 유지할 수 있는 공개 호스트 서비스를 설명하고 있습니다. 
해당 키워드를 가지고 현 시스템의 문제점들을 어떠한 방식으로 개선할 수 있을지 함께 토론해보면 좋을 거 같습니다.

**Comment by KimJuu** [comment]
API!

**Comment by woo00oo** [comment]
답은 api이다
