### ISSUE TITLE
DB의 클라우드 확장성 논의

### ISSUE THREAD

**Issue by sgdo2021** [java-dev-study/Domain-Driven-Design#36]
책에서 보면 CQRS `조회성 저장소` 등 대규모 트래픽과 가용성을 위한 `DB 확장`을 언급한 게 있었습니다.

저희 paytech gbilling 시스템 중에서 DB쪽 확장을 위해 aws 클라우드 전환도 고려하고 상황에 있는데요.
현재 카드번호(암호화 되어 있음, 복호화 가능) 등 신용정보와 클라우드 이전에 따른 법적요구사항 준수여부로

`aws 전환이 어렵다고 생각`하고 있는 것 같습니다. 다른 분들도 이런 상황에 처하고 계시는지 여쭙고 싶고요.
만약 DB 시스템을 클라우드로 확장하는 게 가능하다면 어떻게 가능할 수 있는지 문의드리고 싶습니다.

**Comment by woo00oo** [comment]
뽜이팅
