### ISSUE TITLE
커스텀 에러에 관하여

### ISSUE THREAD

**Issue by Slowth-KIM** [java-dev-study/Domain-Driven-Design#8]
보통 에러가 발생할 경우 커스텀 exception으로 처리하는 경우가 잦은 걸로 알고 있습니다.

예를 들어 게시판이나 회원을 검색할 때 존재하지 않는 게시판 id, 혹은 회원 id로 조회할 경우에는 에러가 발생하게 됩니다. 이런 경우에는 결국 존재하지 않는 id를 조회했기 때문에 발생하는 에러나 다름 업게 됩니다.

 실무에서는 게시판 id가 존재하지 않을 때, 회원 id가 존재하지 않을 때 이렇게 따로 커스텀 exception으로 처리 해야하는지 혹은 비슷한 유형의 에러를 묶어서 따로 핸들링 하는 경우가 있는지가 궁금합니다.

**Comment by woo00oo** [comment]
https://tecoble.techcourse.co.kr/post/2020-08-17-custom-exception/
해당 내용을 참고하시면 좋을듯 싶네요.

저의 개인적인 생각으로는 자바에서 제공해주는 표준 예외를 적극 사용 한 후 커스텀 예외를 사용하는게 더 효과적이라고 생각합니다.
위의 내용들은 토론 주제로 아주 좋은 거 같아요
