### ISSUE TITLE
레거시 DB에서의 애그리거트 경계

### ISSUE THREAD

**Issue by woo00oo** [java-dev-study/Domain-Driven-Design#9]
`P112 특히 레거시 DB를 사용하거나 팀 내 DB 설게 표준을 따라야 한다면 DB 테이블 구조에 맞게 모델을 변경해야 한다.`

애그리거트의 경계가 있는 객체들이지만, 레거시 DB에 의해 경계가 다른 객체들이 하나의 DB 테이블에 insert 해야 할 경우, 모델을 어떤 방식으로 변경해야 DDD 원칙을 망가트리지 않을까요?

**Comment by sgdo2021** [comment]
DB테이블을 결국엔 쪼개야 하지 않을까요?

일단 DDD 원칙적으로 따지자면 도메인 정하기 -> 하위도메인,... -> 엔티티로 쪼개기 -> 그 엔티티에 맞는 DB테이블 만들기

이 순서라 
이런식이면 이미 있는 DB테이블 구조를 다 바꾸워야 하지않을까 싶어요.. 
근데 이게 엄청난 공수가 들어갈 것이니 현실적인 방법을 생각해보니 연결관계를 가진 큰 테이블 -> 작은 테이블로 쪼개는
방식으로 만들고 진행해야 되지 않을까 생각됩니다.
